#!/bin/bash
#===================================================================================
# WIFI MANAGER CLI
# FILE: wifi-manager
#
# DESCRIPTION: Wifi connection manager CLI
#
# AUTHOR: Leonardo Marco
# VERSION: 1.0
# CREATED: 2020.03.29
#===================================================================================


#=== FUNCTION ==================================================================
# NAME: print_signal_bar
# DESCRIPTION: prints a wifi singal bar from a signal value like 33/70
# PARAM1: signal like 33/70
#===============================================================================
function print_signal_bar {
    a=$(echo "$1" | cut -f1 -d "/")
    b=$(echo "$1" | cut -f2 -d "/")
    s=$(((a*100/b)/25+1)); [ $a -eq 0 ] && s=0		# Value from 0 to 5

    case $s in
    0) echo "____" ;;
    1) echo "▂___" ;;
    2) echo "▂▄__" ;;
    3) echo "▂▄▆_" ;;
    [4-9]) echo "▂▄▆█" ;;
    esac
}


#=== FUNCTION ==================================================================
# NAME: scan
# DESCRIPTION: scan visible wifi networks ssid and fill arrays: address, channels, qualities, keys and essids
#===============================================================================
function scan {
    iface="$(iw dev | awk '$1=="Interface"{print $2}' | head -1)"
    [ ! "$(ip link show $iface up)" ] && sudo ip link set dev $iface up
	
    echo -e "\e[1mScaning interface $iface...\e[0m"
    scan="$(iwlist "$iface" scan | egrep "Address|ESSID|Quality|Channel|Encryption key")"
    
    IFS=$'\n'
    addresses=($(echo "$scan" | grep Address: | egrep -o "([0-9A-F]{2}:)+[0-9A-F]{2}"))
    channels=($(echo "$scan" | grep Channel: | cut -f2 -d:))
    qualities=($(echo "$scan" | grep Quality | egrep -o "[0-9]+/[0-9]+"))
    keys=($(echo "$scan" | grep "Encryption key" | cut -f 2 -d:))
    essids=($(echo "$scan" | grep ESSID | cut -f2 -d: | cut -f2 -d\"))
}


#=== FUNCTION ==================================================================
# NAME: list
# DESCRIPTION: print a list of ssids scanned in columns
#===============================================================================
function list {
    (
	# Get current connected SSID
	ssid_current="$(iwgetid $iface | cut -f2 -d: | cut -f2 -d\")"
	
    echo -e "\e[1mNUM␟SIGNAL␟SSID␟CHANNEL␟ENCRYPT\e[0m"
    for n in $(seq 0 $((${#addresses[*]}-1))); do
		addr="${addresses[$n]}"
        ssid="${essids[$n]}"
		[ ! "$ssid" ] && ssid="$addr"
        channel="${channels[$n]}"
        quality="${qualities[$n]}"
        quality="$(print_signal_bar $quality)"
        key="${keys[$n]}"
    
		[ "$ssid" = "$ssid_current" ] && echo -en "\e[32m\e[1m"
        echo -e "[$((n+1))]␟$quality␟$ssid␟$channel␟$key"
		[ "$ssid" = "$ssid_current" ] && echo -en "\e[0m"
    
    done
    ) | column -t -s "␟"
}


#=== FUNCTION ==================================================================
# NAME: disconnect
# DESCRIPTION: disconnect current wifi connection and down wlan iface
# PARAM1: iface to disconnect
#===============================================================================
function disconnect {
	local iface="$1"
	local ssid_current="$(iwgetid $iface | cut -f2 -d: | cut -f2 -d\")"
	echo -e "\n\e[1mDisconnecting from $ssid_current\e[0m"
	killall wpa_supplicant
	dhclient -v -r "$iface"
	ip link set dev $iface down	
}


#=== FUNCTION ==================================================================
# NAME: connect
# DESCRIPTION: connect to ssid asking for password
# PARAM1: ssid to connect
# PARAM2: iface
#===============================================================================
function connect {
	local ssid="$1"
	local ssid_current="$(iwgetid $iface | cut -f2 -d: | cut -f2 -d\")"
	local iface="$2"
	local pass
	
	if [ "$ssid_current" ]; then
		disconnect "$iface"
		[ "$ssid_current" = "$ssid" ] && exit
	fi
	
	# Read pass
	echo -en "\e[1m$ssid\e[0m password: "
	read pass
	
	echo -e "\n\e[1mConnecting to $ssid_current\e[0m"
	[ "$ssid_current" ] && dhclient -v -r "$iface"
	echo
	wpa_supplicant -B -i "$iface" -c <(wpa_passphrase "$ssid" "$pass")
	
	echo -e "\n\e[1mGetting DHCP address\e[0m"
	dhclient -v $iface
}


#=== FUNCTION ==================================================================
# NAME: check_dependences
# DESCRIPTION: checks for script dependences and exit if not found any
#===============================================================================
function check_dependences {
	deps="iwgetid wpa_supplicant dhclient ip sudo"
	deps_err=""
	for d in $deps; do
		! which "$d" &>/dev/null && deps_err="$deps_err${deps_err:+" "}$d"
	done
	
	if [ "$deps_err" ]; then
		echo "Not found dependences: $deps_err" 1>&2
		exit 1
	fi
	
	return 0
}



#=== FUNCTION ==================================================================
# NAME: main function
# DESCRIPTION: start function
#===============================================================================
function main {
	# Select network
    unset n
    while [ ! "$n" ]; do
        clear
        scan
        [ ${#addresses[*]} -eq 0 ] && { sleep 1; continue; }
        list
        echo
		while ! ([ "$n" -le ${#addresses[*]} ]&>/dev/null && [ "$n" -ge 1 ]&>/dev/null); do
        	read -p "Select network: " n
			[ ! "$n" ] && break
		done
    done
	
	connect "${essids[$((n-1))]}" "$iface"
}

main

