#!/bin/bash
# Manage tint2 session file and stop, start and restart tint2 configs

session_file="$HOME/.config/tint2/tint2-sessionfile"
default_tint="$HOME/.config/tint2/tint2rc"

# CHECK SESSION FILE
function check_sessionfile() {
	if [ ! -s "$session_file" ]; then
		if [ ! -s "$default_tint" ]; then
			echo "Tint2 session file or default tint not found!"
			exit 1
		fi

		echo "Creating tint2 session file $session_file with default tint2rc config"
		echo "$default_tint" > "$session_file"
	fi
}

# KILL CURRENT TINT2
function stop() {
	killall tint2
	killall -9 tint2
}

# EXEC SESSION TINTS
function start() {
	local IFS=$'\n'
	while read t; do 
		(setsid tint2 -c "$t" &)
	done < "$session_file"
}


case "${1,,}" in
	""|start|restart)
		check_sessionfile
		stop
		start		
	;;
	stop)
		stop
	*)
	
	;;
esac
