#!/bin/bash
#===================================================================================
# NEOFETCH TTY LOGIN THEME
# FILE: loginfetch.sh
#
# DESCRIPTION: Generate a /etc/issue file based on distro fetch info
#
# AUTHOR: Leonardo Marco
# VERSION: 1.0
# CREATED: 2020.05.06
#
# ASCII LOGOS COPIED FROM UFETCH PROYECT (Copyright 2018, 2019 Joe Schillinger <me@schil.li>)
#===================================================================================

#### COLORS DEFINITION
S_R="\e[0m"            	# Reset all attributes
S_B="\e[1m"             # Style BOLD
S_D="\e[2m"             # Style DIM
S_U="\e[4m"            	# Style UNDERLINE
S_I="\e[7m"             # Style INVERTED
S_DL="\e[K"             # Style DELETE TO END OF LINE
C_D="\e[39m"            # Color DEFAULT
C_R="\e[31m"            # Color RED
C_BR="\e[1m\e[31m"      # Color BOLD RED
C_LR="\e[91m"           # Color LIGHT RED
C_G="\e[32m"            # Color GREEN
C_BG="\e[1m\e[32m"      # Color BOLD GREEN
C_LG="\e[92m"           # Color LIGHT GREEN
C_Y="\e[33m"            # Color YELLOW
C_BY="\e[1m\e[33m"      # Color BOLD YELLOW
C_LY="\e[93m"           # Color LIGHT YELLOW
C_B="\e[34m"            # Color BLUE
C_BB="\e[1m\e[34m"      # Color BOLD BLUE
C_LB="\e[94m"           # Color LIGHT BLUE
C_M="\e[35m"            # Color MAGENTA
C_BM="\e[1m\e[35m"      # Color BOLD MAGENTA
C_LM="\e[95m"           # Color LIGHT MAGENTA
C_C="\e[36m"            # Color CYAN
C_BC="\e[1m\e[36m"      # Color BOLD CYAN
C_LC="\e[96m"           # Color LIGHT CYAN
C_N="\e[90m"            # Color GREY
C_LN="\e[37m"           # Color LIGHT GREY



#### DISTRO LOGOS FUNCTIONS

function logo_debian() {
local c0="${S_R}${C_BR}"
local c1="${S_R}${C_R}"

echo -e "${c0}     _____      ${info1}
${c0}    /  __ \\     ${info2}
${c0}   |  /    |    ${info3}
${c0}   |  ${c1}\\___-     ${info4}
${c1}   -_           ${info5}
${c1}     --_        ${info6}
${c0}                ${info7}${S_R}"
}


function logo_alphine() {
local c0="${S_R}${C_B}"
local c1="${S_R}${C_W}"

echo -e "${c0}     /\ /\         ${info1}
${c0}    /${c1}/ ${c0}\  \        ${info2}
${c0}   /${c1}/   ${c0}\  \       ${info3}
${c0}  /${c1}//    ${c0}\  \      ${info4}
${c0}  ${c1}//      ${c0}\  \     ${info5}
${c0}           \  \    ${info6}
${c0}            \      ${info7}${S_R}"
}


function logo_arch() {
local c0="${S_R}${C_BB}"
local c1="${S_R}${C_B}"

echo -e "${c0}        /\         ${info1}
${c0}       /^^\        ${info2}
${c0}      /\   \       ${info3}
${c0}     /  ${c1}__  \      ${info4}
${c1}    /  (  )  \     ${info5}
${c1}   / __|  |__\\\\\\    ${info6}
${c1}  ///        \\\\\\\\\   ${info7}
${S_R}"
}


function logo_crux() {
local c0="${S_R}${C_W}"
local c1="${S_R}${C_Y}"

echo -e "${c0}      ___     ${info1}
${c0}     (${c1}.· ${c0}|    ${info2}
${c0}     (${c2}<> ${c0}|    ${info3}
${c0}    / ${c1}__  ${c0}\\   ${info4}
${c0}   ( ${c1}/  \\ ${c0}/|  ${info5}
${c2}  _${c0}/\\ ${c1}__)${c0}/${c2}_${c0})  ${info6}
${c2}  \/${c0}-____${c2}\/   ${info7}${S_R}"
}


function logo_fedora() {
local c0="${S_R}${C_BB}"

echo -e "${c0}       _____
${c0}      /   __/  ${info1}
${c0}     |  /      ${info2}
${c0}    _|  |_     ${info3}
${c0}   |_    _|    ${info4}
${c0}     |  |      ${info5}
${c0}   __/  |      ${info6}
${c0}  /____/       ${info7}${S_R}"
}

function logo_gentoo() {
local c0="${S_R}${C_BM}"
local c1="${S_R}${C_M}"

echo -e "${c0}     .-----.      ${info1}
${c0}   .\`    _  \`.    ${info2}
${c0}   \`.   (${c1}_)   ${c0}\`.  ${info3}
${c0}     \`${c1}.        /  ${info4}
${c1}    .\`       .\`   ${info5}
${c1}   /       .\`     ${info6}
${c1}   \____.-\`       ${info7}
${S_R}"
}

function logo_linux() {
local c0="${S_R}${C_W}"
local c1="${S_R}${C_Y}"

echo -e "${c0}      ___       ${info1}
${c0}     (${c1}.. ${c0}\      ${info2}
${c0}     (${c2}<> ${c0}|      ${info3}
${c0}    /${c1}/  \\ ${c0}\\     ${info4}
${c0}   ( ${c1}|  | ${c0}/|    ${info5}
${c2}  _${c0}/\\ ${c1}__)${c0}/${c2}_${c0})    ${info6}
${c2}  \/${c0}-____${c2}\/     ${info7}${S_R}"
} 

function logo_manjaro() {
local c0="${S_R}${C_G}"

echo -e "${c0}  ||||||||| ||||    ${info1}
${c0}  ||||||||| ||||    ${info2}
${c0}  ||||      ||||    ${info3}
${c0}  |||| |||| ||||    ${info4}
${c0}  |||| |||| ||||    ${info5}
${c0}  |||| |||| ||||    ${info6}
${c0}  |||| |||| ||||    ${info7}${S_R}"
} 


function logo_nixos() {
local c0="${S_R}${C_B}"
local c1="${S_R}${C_BB}"

echo -e "${c0}    \\\\\\   ${c1}\\\\\\ //      ${info1}
${c0}   ==\\\\\\___${c1}\\\\\\/ ${c0}//    ${info2}
${c1}     //    \\\\\\$(echo -e "${c0}")//     ${info3}
${c1}  ==//      ${c0}//==    ${info4}
${c1}   //${c0}\\\\\\$(echo -e "${c1}")____${c0}//       ${info5}
${c1}  // ${c0}/\\\\\\   ${c1}\\\\\\==     ${info6}
${c0}    // \\\\\\   ${c1}\\\\\\      ${info7}${S_R}"
} 


function logo_openbsd() {
local c0="${S_R}${C_Y}"
local c1="${S_R}${C_BY}"

echo -e "${c0}       _____      ${info1}
${c0}     \-     -/    ${info2}
${c0}  \_/         \   ${info3}
${c0}  |        ${c1}O O ${c0}|  ${info4}
${c0}  |_  ${c2}<   ${c0})  ${c2}3 ${c0})  ${info5}
${c0}  / \         /   ${info6}
${c0}     /-_____-\    ${info7}${S_R}"
} 


function logo_raspbian() {
local c0="${S_R}${C_BG}"
local c1="${S_R}${C_BR}"

echo -e "${c0}    __  __      ${info1}
${c0}   (_\\)(/_)     ${info2}
${c1}   (_(__)_)     ${info3}
${c1}  (_(_)(_)_)    ${info4}
${c1}   (_(__)_)     ${info5}
${c1}     (__)       ${info6}
${c1}                ${info7}${S_R}"
} 


function logo_antergos() {
local c0="${S_R}${C_B}"
local c1="${S_R}${C_W}"

echo -e "${c0}       .\`\`\`.        ${info1}
${c0}      /     \\       ${info2}
${c0}     /  ${c1}.\`   ${c0}\\      ${info3}
${c0}    / ${c1}.\` .\` . ${c0}\\     ${info4}
${c0}   / ${c1}\` .\`.\` .\` ${c0}\\    ${info5}
${c0}  |    ${c1}\`.\`  \`   ${c0}|   ${info6}
${c0}   \\___________/    ${info7}${S_R}"
} 


function logo_ubuntu() {
local c0="${S_R}${C_W}"
local c1="${S_R}${C_R}"

echo -e "${c1}           _     ${info1}
${c0}       ---${c1}(_)    ${info2}
${c1}   _${c0}/  ---  \\    ${info3}
${c1}  (_)${c0} |   |      ${info4}
${c0}    \\  --- ${c1}_${c0}/    ${info5}
${c0}       ---${c1}(_)    ${info6}
${c0}                 ${info7}${S_R}"
} 


function logo_centos() {
local c0="${S_R}${C_G}"
local c1="${S_R}${C_Y}"
local c2="${S_R}${C_M}"
local c3="${S_R}${C_B}"

echo -e "${c0}   ____${c1}^${c2}____      ${info1}
${c0}   |\\  ${c1}|${c2}  /|      ${info2}
${c0}   | \\ ${c1}|${c2} / |      ${info3}
${c2}  <---- ${c3}---->     ${info4}
${c3}   | / ${c0}|${c1} \\ |      ${info5}
${c3}   |/__${c0}|${c1}__\\|      ${info6}
${c0}       v          ${info7}${S_R}"
} 


function logo_elementary() {
local c0="${S_R}${C_BB}"
local c1="${S_R}${C_B}"

echo -e "${c1}    _______      ${info1}
${c1}   /  ${c0}___  ${c1}\\     ${info2}
${c1}  /  ${c0}|  /  /${c1}\\    ${info3}
${c1}  |${c0}__\\ /  /${c1} |    ${info4}
${c1}  \\   ${c0}/__/${c1}  /    ${info5}
${c1}   \\_______/     ${info6}
${c1}                 ${info7}${S_R}"
} 

function logo_slackware() {
local c0="${S_R}${C_B}"

echo -e "${c0}     ________     ${info1}
${c0}    /  ______|    ${info2}
${c0}    | |______     ${info3}
${c0}    \\______  \\    ${info4}
${c0}     ______| |    ${info5}
${c0}  | |________/    ${info6}
${c0}  |____________   ${info7}${S_R}"
} 

function logo_suse() {
local c0="${S_R}${C_BG}"

echo -e "${c0}      _______      ${info1}
${c0}  -___|   __ \\     ${info2}
${c0}         / ${c1}.${c0}\\ \\    ${info3}
${c0}         \\__/ ${c0}|    ${info4}
${c0}       _______|    ${info5}
${c0}       \\_______    ${info6}
${c0}  --__________/    ${info7}${S_R}"
} 


function logo_void() {
local c0="${S_R}${C_BG}"
local c1="${S_R}${C_G}"

echo -e "${c0}      _______       ${info1}
${c1}      ${c0}\_____ \`-     ${info2}
${c1}   /\   ${c0}___ \`- \    ${info3}
${c1}  | |  ${c0}/   \  | |   ${info4}
${c1}  | |  ${c0}\___/  | |   ${info5}
${c1}   \ \`-_____  ${c0}\/    ${info6}
${c1}    \`-______\       ${info7}${S_R}"
} 


function logo_linuxlite() {
local c0="${S_R}${C_Y}"
local c1="${S_R}${C_W}"

echo -e "${c0}     /\\        ${info1}
${c0}    /  \\       ${info2}
${c0}   / ${c1}/ ${c0}/       ${info3}
${c0}  > ${c1}/ ${c0}/        ${info4}
${c0}  \\ ${c1}\\ ${c0}\\        ${info5}
${c0}   \\_${c1}\\\\${c0}_\\       ${info6}
${c1}      \\        ${info7}${S_R}"
} 



# INFO MESSAGES
info1="${S_R}${S_B}Hostname${S_R}:  $(hostname)"
info2="${S_R}${S_B}OS${S_R}:        $(cat /etc/*release | grep PRETTY_NAME | cut -f2 -d\") $(uname -m)"
info3="${S_R}${S_B}Kernel${S_R}:    $(uname -r) -- $(uname -v)"
info4="${S_R}${S_B}CPU${S_R}:      $(cat /proc/cpuinfo | grep "^model name" | cut -f2 -d: | head -1)"
info5="${S_R}${S_B}Memory${S_R}:    $(free -h | grep "^Mem:" | awk 'BEGIN { OFS=" / " }{ print $3, $2 }')"
info6="${S_R}${S_B}Local IP${S_R}:  $(ip -c=never route get 8.8.8.8 | head -1 | awk 'BEGIN { OFS=" (" }{print $3, $5}'))"
info7="${S_R}${S_B}Uptime${S_R}:    $(uptime -p | sed 's/up //')"


# CREATE ISSUE
issue="$(clear)${S_B}${C_N}\l${S_R}\n"

# ADD DISTRO LOG
distro="linux"
for d in $(declare -F | sed '/logo_/ s/^.*_//'); do
	if cat /etc/*release | grep -i "$d" &>/dev/null; then
		distro="$d"
		break
	fi
done

issue="${issue}$(logo_$distro)"

# DISPLAY SYSTEM USERS
issue="${issue}\n\n${S_B} Users${S_R}: "
for u in $(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | tac); do 
	# Red if lock user:
	[ "$(passwd -S $u 2>/dev/null | cut -f2 -d" ")" = "L" ] && issue="${issue}${C_LR}"
	# Add * to sudo users:
	grep -Po '^sudo.+:\K.*$' /etc/group | grep -w "$u" &>/dev/null && u="${u}*"
	
	issue="${issue}$u${S_R}  " 
done
issue="${issue}\n"

echo -e "$issue"

