#!/bin/bash

# CONFIG
wps_dir="/usr/share/backgrounds/wallpapers-alinz/"


# ROTATE WALLPAPER
# Get all wallpaper paths in array
IFS=$'\n'
wps_paths=($(ls "$wps_dir"/*))

# Get today wallpaper position in array
n=$((${#wps_paths[*]}-1))
n=$((${#wps_paths[*]} % $(date +%e)))


# Get today wallpaper path
wp_path="$(wps_paths[$n]}"
