#!/bin/bash

#### CONFIG ############################################################
wps_dir="/usr/share/backgrounds/wallpapers-alinz/"
########################################################################


# Get all wallpaper paths in array
IFS=$'\n'
wps_paths=($(ls "$wps_dir"/*))

# Get today wallpaper position in array
n=${#wps_paths[*]}
d=$(date +%e)
if [ $n -gt 30 ]; then
	n=$((n%d))
else
	n=$((d%n))
fi

# Get today wallpaper path
wp_default="$(wps_paths[$n]}"

# Set wallpaper to all users
for f in /home/*/.config/nitrogen/bg-saved; do
	sed -i 's/^file *= *.*/file='$(echo "$wp_default" | sed 's/\//\\\//g' )'/' "$f"
done
