#!/bin/bash

#### CONFIG ############################################################
wps_dir="/usr/share/backgrounds/wallpapers-alinz/"
########################################################################


# Get all wallpaper paths in array
IFS=$'\n'
wps_paths=($(ls "$wps_dir"/*))

# Get today wallpaper position in array
n=${#wps_paths[*]}										# Num of files
shopt -s extglob; d=$(date +%j); d=${d##+(0)}			# Day of year
n=$((d%n))												# Today wp position

# Get today wallpaper path
wp_default="${wps_paths[$n]}"

# Set wallpaper to all users
for f in /home/*/.config/nitrogen/bg-saved.cfg; do
	sed -i 's/^file *= *.*/file='$(echo "$wp_default" | sed 's/\//\\\//g' )'/' "$f"
done
