alias ls='ls --color=auto'        #DEBIAN-OPENBOX
alias ll='ls -l --color=auto'     #DEBIAN-OPENBOX
alias egrep='egrep --color=auto'  #DEBIAN-OPENBOX
alias fgrep='fgrep --color=auto'  #DEBIAN-OPENBOX
alias rgrep='rgrep --color=auto'  #DEBIAN-OPENBOX
alias grep='grep --color=auto'    #DEBIAN-OPENBOX
