#!/bin/bash

options=" ⏻\tPower off
 🗘\tReboot
 ⏸\tSuspend
 ⏾\tHibernate
 🗙\tLogout
 🗝 \tLock session"

if [ $# -eq 0 ]; then
    echo -e "$options"

elif [ "$1" = "show" ]; then
    rofi -theme openbox-menu -show Action -modi "Action:$(readlink -f "$0")"

else
    case "$@" in
    *"Logout")
        openbox --exit
        ;;
    *"Lock session")
        x-locker
        ;;
    *"Power off")
        systemctl poweroff
        ;;
    *"Reboot")
        systemctl reboot
        ;;
    *"Suspend")
        systemctl suspend
        ;;
    *"Hibernate")
        systemctl hibernate
        ;;
    esac
fi
