#!/bin/bash

#### CONFIG ############################################################
wps_dir="/usr/share/backgrounds/wallpapers-alinz/"
########################################################################

# Checks
[ ! -d "$wps_dir" ] && exit 1


# Put all wallpaper paths in array
IFS=$'\n'
wps_paths=($(ls "$wps_dir"/*))							# Array with all wallpapers path

# Get today wallpaper position in array
n=${#wps_paths[*]}										# Num of items in array
shopt -s extglob; d=$(date +%j); d=${d##+(0)}			# Today day of year
n=$((d%n))												# Today array position

# Get today wallpaper path
wp_selected="${wps_paths[$n]}"
echo -e "Selected wallpaper is:\t\t$wp_selected"

# Generate link
wp_link="$wps_dir/wp-rotate.${wp_selected##*.}"
echo -e "Creating wallpaper link in:\t$wp_link"
ln -sf "$wp_selected" "$wp_link"

