#!/bin/bash

options="Logout
Lock session
Power off
Reboot
Suspend
Hibernate"

if [ $# -eq 0 ]; then
	echo "$options"

elif [ "$1" = "show" ]; then
	rofi -theme box -show "Power menu" -modi "Power menu":"$(readlink -f "$0")"

else
	case $@ in
	Logout)
		openbox --exit
		;;
	Lock session)
		physlock
		;;
	Power off)
		systemctl poweroff
		;;
	Reboot)
		systemctl reboot
		;;
	Suspend) 
		systemctl suspend
		;;
	Hibernate)
		systemctl hibernate
		;;
	esac
fi
