#!/bin/bash

# NO CUPS
if [ "$1" = "-I" ]; then
    # INSTALL CUPS
    if ! dpkg -s cups&>/dev/null; then
        echo "CUPS is not installed"
        while true; do 
            read -p "Install cups? (Y/n) " q;   
            [ "${q,,}" = "n" ] && exit
            ([ ! "$q" ] || [ "${q,,}" = "y" ]) && break
        done
        echo
        sudo apt-get install -y cups  
        # Adduser to lpadmin    
         x-www-browser "http://localhost:631"
    # START CUPS
    else
        echo hola
    fi

# OPEN CUPS ADMIN
elif systemctl status cups&>/dev/null; then
    x-www-browser "http://localhost:631"
    exit

# CALL TO INSTALL CUPS
else
    x-terminal-emulator -e "$(readlink -f "$0")" -I
fi
