#!/bin/bash
#===================================================================================
# FILE: conky-session
# DESCRIPTION: manage conky processes for start, restart and stop all conky instances
# AUTHOR: Leonardo Marco
# VERSION: 1.0
# CREATED: 2020.04.09
# LICENSE: GNU General Public License v3.0
#===================================================================================

conkys_path="$HOME/.config/conky/"


#=== FUNCTION ======================================================================
# NAME: stop
# DESCRIPTION: stop all conky process
#===================================================================================
function stop() {
	killall conky
	killall -9 conky
}


#=== FUNCTION ======================================================================
# NAME: start
# DESCRIPTION: load each .conkyrc file in user conky path
#===================================================================================
function start() {
	local IFS=$'\n'
	for f in $(ls "$conkys_path"/*.conkyrc); do
		conky -c "$f" &
	done 
}


# EXEC ACTION ACCORDING $1
case "${1,,}" in
	""|start|restart)
		stop
		start		
	;;
	stop)	
		stop	
	;;
	*)	
		echo "Usage: conky-session [start|stop|restart]"
	;;
esac
