#!/bin/bash
#===================================================================================
# FILE: conky-session
# DESCRIPTION: manage conky session file and stop, start and restart conky configs
# AUTHOR: Leonardo Marco
# VERSION: 1.0
# CREATED: 2020.04.09
# LICENSE: GNU General Public License v3.0
#===================================================================================

session_file="$HOME/.config/conky/conky-sessionfile"
default_conky="$HOME/.conky"

#=== FUNCTION ======================================================================
# NAME: check_sessionfile
# DESCRIPTION: checks if user session file exists or create it with conky default config
#===================================================================================
function check_sessionfile() {
	if [ ! -s "$session_file" ]; then
		if [ ! -s "$default_tint" ]; then
			echo "Conky session file or default conky not found!"
			exit 1
		fi

		echo "Creating conky session file $session_file with default conky config"
		echo "$default_conky" > "$session_file"
	fi
}


#=== FUNCTION ======================================================================
# NAME: stop
# DESCRIPTION: stop all tint2 process
#===================================================================================
function stop() {
	killall conky
	killall -9 conky
}


#=== FUNCTION ======================================================================
# NAME: start
# DESCRIPTION: read user conky session file and start all conkys
#===================================================================================
function start() {
	local IFS=$'\n'
	cat "$session_file" | sort -u | while read f; do 
		conky -c "$f" &
	done 
}



# PARAMETERS PROCESSING
case "${1,,}" in
	""|start|restart)
		check_sessionfile
		stop
		start		
	;;
	stop)	
		stop	
	;;
	*)	
		echo "Usage: conky-session [start|stop|restart]"
	;;
esac
