"OPTIONS
syntax on                       "Syntax highlight
set mouse=r                     "Allow copy and paste with mouse
set number                      "Show line numbers
set hlsearch                    "Hightlight all matches on search
set ignorecase                  "Search are case insensitive
set smartcase                   "Search case sensitive if any caps are used
set incsearch                   "Show matches highlight when typing
set tabstop=4                   "Tab=4 spaces
"set autoindent                 "Auto add tabs
let g:netrw_banner = 0          "Hide header in :Explore mode
 

"THEME
set background=dark             "Background color
colorscheme hybrid_material     "https://github.com/kristijanhusak/vim-hybrid-material
let g:airline_theme = "hybrid"
let g:enable_bold_font = 1
let g:enable_italic_font = 1
